### ISSUE TITLE
Create rSAI branch of the dapp

### ISSUE THREAD

**Issue by hellwolf** [rtoken-project/rdai-app#5]
ACs:

- [x] automatically deployed to the s3://rsai.rdai.money
- [x] create a cloudfront distribution for s3://rsai.rdai.money
- [x] setup domain: https://rsai.rdai.money/
- [x] show a top banner pointing to the migration path of sai to dai

**Comment by vrortvedt** [comment]
The rsai.rdai.money top banner should also explain that that the app is for using rSAI only, and linking to the rDAI (MCD) app

**Comment by hellwolf** [comment]
well done!
